# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # setup_ci
    create_keychain(
    name: "my_custom_keychain",
    password: "my_custom_keychain_2025",
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    )
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner",
    clean: true,
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
        "com.expensetrackeroffline.expense-tracker-lite" => "Expense - Inovola"
      } 
    },
     # Skip automatic profile detection if you provide profiles
     skip_profile_detection: true
     )
    upload_to_testflight
  end
end
